---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-masquerade
  name: vmi-masquerade
spec:
  domain:
    cpu:
      cores: 1
      model: Nehalem          
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: testmasquerade
        ports:
        - name: http
          port: 80
          protocol: TCP
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: testmasquerade
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:v0.11.0
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
        yum install -y nginx
        systemctl enable nginx
        systemctl start nginx
    name: cloudinitdisk
