apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-ovs2
  name: vmi-ovs2
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: default
      - bridge: {}
        name: ovs-net-1
      - bridge: {}
        name: ovs-net-2-vlan
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: ovs-net-1
    name: ovs-net-1
  - multus:
      networkName: ovs-net-2-vlan
    name: ovs-net-2-vlan
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
        ip addr add 11.0.1.12/24 dev eth1
        ip link set dev eth1 up
        ip addr add 11.0.2.12/24 dev eth2
        ip link set dev eth2 up
    name: cloudinitdisk
