apiVersion: v1
kind: Pod
metadata:
  name: samplepod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: ovs-net-1,ovs-net-2-vlan
spec:
  containers:
  - name: samplepod-1
    command: ["sh", "-c", "ip address add 11.0.1.1/24 dev net1; ip link set up net1; ip address add 11.0.2.1/24 dev net2; ip link set up net2; sleep 99999"]
    image: alpine
    securityContext:
      privileged: true
