---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-windows
  labels:
    kubevirt.io: ""
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

  selector:
    matchLabels:
      os: "windows-demo"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-windows
  labels:
    kubevirt.io: ""
    os: "windows-demo"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.66.137.181
    path: /home/images
